version: '3.1'

services:
  php:
    build: ./php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql

volumes:
  mysql-data:
